### ISSUE TITLE
А зачем ты surefire-plugin добавила как dependency к проекту?

### ISSUE THREAD

**Issue by khda91** [EleKon612/ElenaKonovalova_LevelUp#1]
https://github.com/EleKon612/ElenaKonovalova_LevelUp/blob/9cda4128a9ed6d91b87ee17dd954ced92e159546/pom.xml#L91-L95

Все плагины указываются в секции build.plugins

**Comment by EleKon612** [comment]
У меня не работал surefire plugin (был выделен красным), потом я его добавила в dependency, потом исправила номер версии и заработало, а из dependency забыла убрать.

  
>Среда, 15 июня 2022, 21:13 +03:00 от Khodakovsky Dmitry ***@***.***>:
> 
> 
>https://github.com/EleKon612/ElenaKonovalova_LevelUp/blob/9cda4128a9ed6d91b87ee17dd954ced92e159546/pom.xml#L91
>Все плагины указываются в секции build.plugins
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  <EleKon612/ElenaKonovalova_LevelUp/issues/1 @ github . com> 
 
 
С уважением,

Елена Коновалова
