### ISSUE TITLE
А зачем копия класса в src/main проекта?

### ISSUE THREAD

**Issue by khda91** [EleKon612/ElenaKonovalova_LevelUp#2]
https://github.com/EleKon612/ElenaKonovalova_LevelUp/blob/9cda4128a9ed6d91b87ee17dd954ced92e159546/src/main/java/ru/levelup/qa/at/calculator/Calculator.java#L1-L83

Для данной работы `src/main` папка должна быть пустой. Не должно быть в ней никаких классов.
Сам класс `Calculator` должен браться из **jar** файла

**Comment by EleKon612** [comment]
у меня сначала не получалось работать с калькулятором в папке libs и я попробовала его перенести в src/main (по аналогии с тем калькулятором, который разбирали на занятии), и все заработало. Сейчас тогда попробую удалить из src/main, я создала только что ветку homework2, и потом попробую создать pull request как написано в инструкции к выполнению дз.

  
>Среда, 15 июня 2022, 21:16 +03:00 от Khodakovsky Dmitry ***@***.***>:
> 
> 
>https://github.com/EleKon612/ElenaKonovalova_LevelUp/blob/9cda4128a9ed6d91b87ee17dd954ced92e159546/src/main/java/ru/levelup/qa/at/calculator/Calculator.java#L1-L83
>Для данной работы src/main папка должна быть пустой. Не должно быть в ней никаких классов.
>Сам класс Calculator должен браться из  jar файла
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  <EleKon612/ElenaKonovalova_LevelUp/issues/2 @ github . com> 
 
 
С уважением,

Елена Коновалова
