### ISSUE TITLE
Для чего используются все Before и After hooks?

### ISSUE THREAD

**Issue by khda91** [EleKon612/ElenaKonovalova_LevelUp#3]
https://github.com/EleKon612/ElenaKonovalova_LevelUp/blob/9cda4128a9ed6d91b87ee17dd954ced92e159546/src/test/java/ru/levelp/at/lesson0304/build/unit/testing/tools/homework/MyCalculatorHomeworkAllClassesTest.java#L22-L43

https://github.com/EleKon612/ElenaKonovalova_LevelUp/blob/9cda4128a9ed6d91b87ee17dd954ced92e159546/src/test/java/ru/levelp/at/lesson0304/build/unit/testing/tools/homework/MyCalculatorHomeworkAllClassesTest.java#L219-L241

Для данного задания использовать все эти методы смысла особого нет. Их можно удалить

**Comment by EleKon612** [comment]
я включала запись занятия и повторяла абсолютно все действия, иначе не понять и не запомнить. удалять не хочется, можно оставить с пометкой, что это необязательные методы?

  
>Среда, 15 июня 2022, 21:21 +03:00 от Khodakovsky Dmitry ***@***.***>:
> 
> 
>https://github.com/EleKon612/ElenaKonovalova_LevelUp/blob/9cda4128a9ed6d91b87ee17dd954ced92e159546/src/test/java/ru/levelp/at/lesson0304/build/unit/testing/tools/homework/MyCalculatorHomeworkAllClassesTest.java#L22-L43
>https://github.com/EleKon612/ElenaKonovalova_LevelUp/blob/9cda4128a9ed6d91b87ee17dd954ced92e159546/src/test/java/ru/levelp/at/lesson0304/build/unit/testing/tools/homework/MyCalculatorHomeworkAllClassesTest.java#L219-L241
>Для данного задания использовать все эти методы смысла особого нет. Их можно удалить
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  <EleKon612/ElenaKonovalova_LevelUp/issues/3 @ github . com> 
 
 
С уважением,

Елена Коновалова
