### ISSUE TITLE
Не выполнено одно из требований домашнего задания

### ISSUE THREAD

**Issue by khda91** [EleKon612/ElenaKonovalova_LevelUp#4]
https://github.com/EleKon612/ElenaKonovalova_LevelUp/blob/9cda4128a9ed6d91b87ee17dd954ced92e159546/src/test/java/ru/levelp/at/lesson0304/build/unit/testing/tools/homework/MyCalculatorHomeworkAllClassesTest.java#L52-L208

В требованиях к домашнему заданию сказано, что для каждого вида операций должен быть создан отдельный класс. Сейчас все операции размещены в одном классе

**Comment by EleKon612** [comment]
перепутала класс с методом, исправлю

  
>Среда, 15 июня 2022, 21:23 +03:00 от Khodakovsky Dmitry ***@***.***>:
> 
> 
>https://github.com/EleKon612/ElenaKonovalova_LevelUp/blob/9cda4128a9ed6d91b87ee17dd954ced92e159546/src/test/java/ru/levelp/at/lesson0304/build/unit/testing/tools/homework/MyCalculatorHomeworkAllClassesTest.java#L52-L208
>В требованиях к домашнему заданию сказано, что для каждого вида операций должен быть создан отдельный класс. Сейчас все операции размещены в одном классе
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you are subscribed to this thread. Message ID:  <EleKon612/ElenaKonovalova_LevelUp/issues/4 @ github . com> 
 
 
С уважением,

Елена Коновалова
